/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendenciasRouteImport } from './routes/tendencias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LogRouteImport } from './routes/log'
import { Route as IndexRouteImport } from './routes/index'

const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/perfil': typeof PerfilRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/perfil': typeof PerfilRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/perfil': typeof PerfilRoute
  '/tendencias': typeof TendenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/log' | '/perfil' | '/tendencias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/log' | '/perfil' | '/tendencias'
  id: '__root__' | '/' | '/log' | '/perfil' | '/tendencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  PerfilRoute: typeof PerfilRoute
  TendenciasRoute: typeof TendenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  PerfilRoute: PerfilRoute,
  TendenciasRoute: TendenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
